name: Docker build

on:
  workflow_dispatch:

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ubuntu_host_version: ["23.04","23.10"]
        python_version: ["3.10.7", "3.11.7", "3.12.1", "3.13.0"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            "BASE_IMAGE=ubuntu:${{ matrix.ubuntu_host_version }}"
            "PYTHON_VERSION=${{ matrix.python_version }}"
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/cpython:${{ matrix.python_version }}_${{ matrix.ubuntu_host_version }}"
