name: Docker build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ubuntu_host_version: ["23.10"]
        python_version: ["3.12.1"]
    steps:
      -
        name: Prepare
        run: |
          echo "${{ matrix.python_version }}_${{ matrix.ubuntu_host_version }}"
